// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: arthmetic_svc.pb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArithmeticClient is the client API for Arithmetic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArithmeticClient interface {
	GetAddition(ctx context.Context, in *OperationParams, opts ...grpc.CallOption) (*Answer, error)
	GetSubtraction(ctx context.Context, in *OperationParams, opts ...grpc.CallOption) (*Answer, error)
	GetMultiplication(ctx context.Context, in *OperationParams, opts ...grpc.CallOption) (*Answer, error)
	GetDivision(ctx context.Context, in *OperationParams, opts ...grpc.CallOption) (*Answer, error)
}

type arithmeticClient struct {
	cc grpc.ClientConnInterface
}

func NewArithmeticClient(cc grpc.ClientConnInterface) ArithmeticClient {
	return &arithmeticClient{cc}
}

func (c *arithmeticClient) GetAddition(ctx context.Context, in *OperationParams, opts ...grpc.CallOption) (*Answer, error) {
	out := new(Answer)
	err := c.cc.Invoke(ctx, "/pb.Arithmetic/GetAddition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmeticClient) GetSubtraction(ctx context.Context, in *OperationParams, opts ...grpc.CallOption) (*Answer, error) {
	out := new(Answer)
	err := c.cc.Invoke(ctx, "/pb.Arithmetic/GetSubtraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmeticClient) GetMultiplication(ctx context.Context, in *OperationParams, opts ...grpc.CallOption) (*Answer, error) {
	out := new(Answer)
	err := c.cc.Invoke(ctx, "/pb.Arithmetic/GetMultiplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmeticClient) GetDivision(ctx context.Context, in *OperationParams, opts ...grpc.CallOption) (*Answer, error) {
	out := new(Answer)
	err := c.cc.Invoke(ctx, "/pb.Arithmetic/GetDivision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArithmeticServer is the server API for Arithmetic service.
// All implementations should embed UnimplementedArithmeticServer
// for forward compatibility
type ArithmeticServer interface {
	GetAddition(context.Context, *OperationParams) (*Answer, error)
	GetSubtraction(context.Context, *OperationParams) (*Answer, error)
	GetMultiplication(context.Context, *OperationParams) (*Answer, error)
	GetDivision(context.Context, *OperationParams) (*Answer, error)
}

// UnimplementedArithmeticServer should be embedded to have forward compatible implementations.
type UnimplementedArithmeticServer struct {
}

func (UnimplementedArithmeticServer) GetAddition(context.Context, *OperationParams) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddition not implemented")
}
func (UnimplementedArithmeticServer) GetSubtraction(context.Context, *OperationParams) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubtraction not implemented")
}
func (UnimplementedArithmeticServer) GetMultiplication(context.Context, *OperationParams) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultiplication not implemented")
}
func (UnimplementedArithmeticServer) GetDivision(context.Context, *OperationParams) (*Answer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDivision not implemented")
}

// UnsafeArithmeticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArithmeticServer will
// result in compilation errors.
type UnsafeArithmeticServer interface {
	mustEmbedUnimplementedArithmeticServer()
}

func RegisterArithmeticServer(s grpc.ServiceRegistrar, srv ArithmeticServer) {
	s.RegisterService(&Arithmetic_ServiceDesc, srv)
}

func _Arithmetic_GetAddition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).GetAddition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Arithmetic/GetAddition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).GetAddition(ctx, req.(*OperationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arithmetic_GetSubtraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).GetSubtraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Arithmetic/GetSubtraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).GetSubtraction(ctx, req.(*OperationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arithmetic_GetMultiplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).GetMultiplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Arithmetic/GetMultiplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).GetMultiplication(ctx, req.(*OperationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arithmetic_GetDivision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmeticServer).GetDivision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Arithmetic/GetDivision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmeticServer).GetDivision(ctx, req.(*OperationParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Arithmetic_ServiceDesc is the grpc.ServiceDesc for Arithmetic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arithmetic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Arithmetic",
	HandlerType: (*ArithmeticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddition",
			Handler:    _Arithmetic_GetAddition_Handler,
		},
		{
			MethodName: "GetSubtraction",
			Handler:    _Arithmetic_GetSubtraction_Handler,
		},
		{
			MethodName: "GetMultiplication",
			Handler:    _Arithmetic_GetMultiplication_Handler,
		},
		{
			MethodName: "GetDivision",
			Handler:    _Arithmetic_GetDivision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arthmetic_svc.pb.proto",
}
